env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  linebreak-style: 
    - "error"
    - "windows"
  no-use-before-define: 0
  react/jsx-filename-extension: 
    - 1
    - { "extensions": [".ts", ".tsx"] }
  semi: 
    - 2
    - "never"
  import/no-unresolved:
    - 0
  import/extensions:
    - 0
  react/button-has-type:
    - 0
  no-param-reassign: [2, { "props": false }]
  no-shadow:
    - 0
  jsx-a11y/no-static-element-interactions:
    - 0
  jsx-a11y/click-events-have-key-events:
    - 0
  no-unused-vars:
    - 0
  func-names:
    - 0
  no-console:
    - 0
settings:
        import/resolver:
            node:
                extensions:
                    - ".js"
                    - ".ts"
                    - ".tsx"